using System.Text.Json;
using VibeSuperTonic.Core.Models;
using Xunit;

namespace VibeSuperTonic.Core.Tests;

/// <summary>
/// The curated catalog — both the type that reads it and <b>the actual file that
/// ships</b>.
///
/// <para><b>Why the shipped file is under test and not a fixture.</b>
/// <c>piper-voices.json</c> is generated by <c>build/gen-piper-catalog.py</c>
/// against a pinned upstream revision, and regenerating it is a thing someone
/// will do — when the revision moves, when the licence policy changes, when a
/// voice is added. The invariants below are the ones the product depends on and
/// none of them are checked by the generator running successfully: a catalog can
/// be perfectly well-formed JSON and still carry a voice with no hash, two
/// entries with the same id, or a file whose name does not match the directory
/// the store will look in. The file is linked into the test output by the csproj,
/// so this fails in the ordinary test run rather than in the field.</para>
/// </summary>
public class PiperCatalogTests
{
    private static PiperCatalog Shipped()
    {
        // Linked from the repository root by the csproj, so this is the file the
        // packers copy into the archive rather than a copy of it.
        string path = Path.Combine(AppContext.BaseDirectory, "Resources", "piper-voices.json");
        Assert.True(File.Exists(path), $"the shipped catalog is not in the test output at {path}");
        var c = PiperCatalog.TryLoad(Path.GetDirectoryName(path)!);
        Assert.NotNull(c);
        return c!;
    }

    // -------------------------------------------------------- the shipped file

    [Fact]
    public void The_shipped_catalog_loads_and_is_not_empty()
    {
        var c = Shipped();
        Assert.NotEmpty(c.Voices);
        Assert.NotNull(c.Source);
        Assert.False(string.IsNullOrWhiteSpace(c.Source!.Revision));
    }

    [Fact]
    public void Every_shipped_voice_is_pinned_by_size_and_sha256()
    {
        // The entire integrity story. A voice with a blank hash downloads and is
        // accepted, which is the one failure mode a pinned catalog exists to
        // prevent — and ModelDownloader treats an empty Sha256 as "verified".
        foreach (var v in Shipped().Voices)
        {
            Assert.Equal(2, v.Files.Count);
            foreach (var f in v.Files)
            {
                Assert.True(f.Bytes > 0, $"{v.Id}/{f.Name} has no size");
                Assert.True(f.Sha256.Length == 64, $"{v.Id}/{f.Name} has no sha256");
                Assert.Matches("^[0-9a-f]{64}$", f.Sha256);
            }
        }
    }

    [Fact]
    public void Every_shipped_voice_carries_a_licence_a_person_can_be_shown()
    {
        // Trap 7: the download is gated on the voice's own terms, so a voice
        // whose terms are blank is a gate with nothing on it. The generator
        // excludes 33 upstream voices for exactly this; this is what proves the
        // exclusion survived into the file.
        foreach (var v in Shipped().Voices)
        {
            Assert.False(string.IsNullOrWhiteSpace(v.Licence.Name), $"{v.Id} has no licence text");
            Assert.False(string.IsNullOrWhiteSpace(v.Licence.Class), $"{v.Id} has no licence class");
            Assert.Contains(v.Licence.Class, new[] { "public", "by", "apache", "by-sa", "agpl", "nc" });
        }
    }

    [Fact]
    public void Shipped_ids_are_unique_and_name_their_own_files()
    {
        // The id IS the directory name and the filename stem — models/piper/<id>/<id>.onnx.
        // A mismatch installs a voice the store cannot see, and the download
        // reports success while doing it.
        var c = Shipped();
        Assert.Equal(c.Voices.Count, c.Voices.Select(v => v.Id).Distinct(StringComparer.OrdinalIgnoreCase).Count());

        foreach (var v in c.Voices)
        {
            Assert.Contains(v.Files, f => f.Name == v.Id + ".onnx");
            Assert.Contains(v.Files, f => f.Name == v.Id + ".onnx.json");
        }
    }

    [Fact]
    public void A_shipped_id_is_its_language_name_and_quality()
    {
        foreach (var v in Shipped().Voices)
            Assert.Equal($"{v.Language.Code}-{v.Name}-{v.Quality}", v.Id);
    }

    [Fact]
    public void Every_shipped_voice_states_a_rate_the_sink_can_be_tuned_to()
    {
        // Since P3 the sink follows the voice, so this number is what the machine
        // will actually play. Upstream trains at 16 kHz or 22.05 kHz and nothing
        // else; a third value means the config parse found something unexpected.
        foreach (var v in Shipped().Voices)
            Assert.True(v.SampleRate is 16000 or 22050, $"{v.Id} reports {v.SampleRate} Hz");
    }

    [Fact]
    public void A_multi_speaker_voice_names_every_speaker_it_claims()
    {
        // PiperOptions.SpeakerId indexes this list. A voice claiming 109 speakers
        // with an empty list gives the picker nothing to show and the render a
        // sid it cannot justify.
        foreach (var v in Shipped().Voices.Where(v => v.Speakers > 1))
            Assert.Equal(v.Speakers, v.SpeakerNames.Count);

        foreach (var v in Shipped().Voices.Where(v => v.Speakers == 1))
            Assert.Empty(v.SpeakerNames);
    }

    [Fact]
    public void Shipped_urls_all_point_at_the_pinned_revision()
    {
        // The revision is the whole reason the hashes stay valid. A URL that
        // slipped to main is one upstream can change under us, and it would keep
        // working right up until they did.
        var c = Shipped();
        string rev = c.Source!.Revision;
        foreach (var v in c.Voices)
            foreach (var f in v.Files)
                Assert.Contains($"/resolve/{rev}/", f.Url);
    }

    [Fact]
    public void The_non_ascii_voice_id_is_escaped_in_its_url()
    {
        // pt_PT-tugão-medium. The id keeps its ã — it is a directory name and
        // Linux and Windows both take it — but the URL must not, because every
        // HTTP client has its own rule for a raw non-ASCII path and a pinned
        // catalog is not the place for those to differ.
        var v = Shipped().Find("pt_PT-tugão-medium");
        if (v is null) return;                       // the catalog may not always carry it
        foreach (var f in v.Files)
            Assert.All(f.Url, ch => Assert.True(ch < 128, $"raw non-ASCII in {f.Url}"));
    }

    // ------------------------------------------------------------- the reader

    private const string Sample = """
    {
      "version": "1",
      "source": { "repo": "r", "revision": "v1", "generated": "2026-08-25", "policy": "C" },
      "voices": [
        { "id": "en_US-x-high",   "name": "x", "quality": "high",
          "language": { "code": "en_US", "english": "English", "native": "English", "country": "United States" },
          "sampleRate": 22050, "speakers": 1, "speakerNames": [],
          "licence": { "name": "CC0", "class": "public", "url": "u" },
          "files": [ { "name": "en_US-x-high.onnx",      "url": "https://h/a", "sha256": "aa", "bytes": 100 },
                     { "name": "en_US-x-high.onnx.json", "url": "https://h/b", "sha256": "bb", "bytes": 10 } ] },
        { "id": "en_US-x-medium", "name": "x", "quality": "medium",
          "language": { "code": "en_US", "english": "English", "native": "English", "country": "United States" },
          "sampleRate": 22050, "speakers": 1, "speakerNames": [],
          "licence": { "name": "CC0", "class": "public", "url": "u" },
          "files": [ { "name": "en_US-x-medium.onnx",      "url": "https://h/c", "sha256": "cc", "bytes": 50 },
                     { "name": "en_US-x-medium.onnx.json", "url": "https://h/d", "sha256": "dd", "bytes": 5 } ] }
      ]
    }
    """;

    [Fact]
    public void Tiers_of_one_voice_come_back_best_first()
    {
        var c = PiperCatalog.TryParse(Sample)!;
        var tiers = c.Tiers(c.Find("en_US-x-medium")!);
        Assert.Equal(new[] { "en_US-x-high", "en_US-x-medium" }, tiers.Select(t => t.Id));
    }

    [Fact]
    public void The_preferred_tier_is_the_highest_available()
    {
        var c = PiperCatalog.TryParse(Sample)!;
        Assert.Equal("en_US-x-high", c.PreferredTier("x", "en_US")!.Id);
    }

    [Fact]
    public void Lookup_is_case_insensitive_because_ids_come_from_files_people_edit()
    {
        var c = PiperCatalog.TryParse(Sample)!;
        Assert.Equal("en_US-x-high", c.Find("EN_us-X-HIGH")!.Id);
        Assert.Null(c.Find("nope"));
        Assert.Null(c.Find(null));
    }

    [Fact]
    public void A_catalog_that_is_absent_or_unreadable_is_null_rather_than_a_throw()
    {
        // Same contract as Manifest.TryLoad: no catalog means the Voices tab
        // lists what is installed and offers nothing new — degraded, not broken.
        Assert.Null(PiperCatalog.TryLoad(Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString())));
        Assert.Null(PiperCatalog.TryParse("{ not json"));
        Assert.Null(PiperCatalog.TryParse(""));
    }

    [Fact]
    public void Entries_that_cannot_be_downloaded_are_dropped_rather_than_carried_to_the_ui()
    {
        const string broken = """
        { "version": "1", "voices": [
          { "id": "",      "files": [ { "name": "a.onnx", "url": "https://h/a", "sha256": "x", "bytes": 1 } ] },
          { "id": "nofile","files": [] },
          { "id": "badurl","files": [ { "name": "b.onnx", "url": "not a url",   "sha256": "x", "bytes": 1 } ] },
          { "id": "ok",    "files": [ { "name": "c.onnx", "url": "https://h/c", "sha256": "x", "bytes": 1 } ] } ] }
        """;
        var c = PiperCatalog.TryParse(broken)!;
        Assert.Equal(new[] { "ok" }, c.Voices.Select(v => v.Id));
    }

    // -------------------------------------------- the bridge to ModelDownloader

    [Fact]
    public void A_voice_becomes_a_manifest_rooted_at_the_store_folder()
    {
        var c = PiperCatalog.TryParse(Sample)!;
        var m = PiperCatalog.ManifestFor(c.Find("en_US-x-high")!, "piper");

        Assert.Equal(
            new[] { "piper/en_US-x-high/en_US-x-high.onnx", "piper/en_US-x-high/en_US-x-high.onnx.json" },
            m.Files.Select(f => f.Path));
        Assert.Equal("aa", m.Files[0].Sha256);
        Assert.Equal(100, m.Files[0].Bytes);
    }

    [Fact]
    public void The_weights_are_always_downloaded_before_the_config()
    {
        // The store's rule is "both files or neither", so an interrupted install
        // must leave weights-without-config rather than the other way round —
        // that is the state that cannot be mistaken for a voice. Reversing the
        // catalog's order must not reverse this.
        var c = PiperCatalog.TryParse(Sample)!;
        var voice = c.Find("en_US-x-high")!;
        voice.Files.Reverse();

        var m = PiperCatalog.ManifestFor(voice, "piper");
        Assert.EndsWith(".onnx", m.Files[0].Path);
        Assert.EndsWith(".onnx.json", m.Files[1].Path);
    }

    [Fact]
    public void Licence_classes_answer_the_two_questions_a_gate_asks()
    {
        Assert.True(new PiperLicence("CC BY-NC-SA 4.0", "nc", "u").IsNonCommercial);
        Assert.False(new PiperLicence("CC0", "public", "u").IsNonCommercial);
        Assert.False(new PiperLicence("CC0", "public", "u").RequiresAttribution);
        Assert.True(new PiperLicence("CC BY 4.0", "by", "u").RequiresAttribution);
    }

    [Fact]
    public void A_language_display_name_reads_as_a_person_would_say_it()
    {
        Assert.Equal("English (United States)",
            new PiperCatalogLanguage("en_US", "English", "English", "United States").Display());
        Assert.Equal("Welsh",
            new PiperCatalogLanguage("cy_GB", "Welsh", "Cymraeg", "").Display());
    }

    [Fact]
    public void The_shipped_catalog_is_the_one_the_generator_produces()
    {
        // Not a round-trip of our own serializer — a check that every property
        // the reader needs is actually present under the name it expects. A
        // renamed field in the generator deserializes to a default and shows up
        // as a voice with 0 speakers and no rate, which reads as data rather
        // than as a bug.
        using var doc = JsonDocument.Parse(
            File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Resources", "piper-voices.json")));
        var first = doc.RootElement.GetProperty("voices")[0];
        foreach (string name in new[]
                 { "id", "name", "language", "quality", "sampleRate", "speakers", "speakerNames", "licence", "files" })
            Assert.True(first.TryGetProperty(name, out _), $"the generator no longer emits '{name}'");
    }
}
